master:
  push:
    - runner:
        cpus: 64
      services:
        - docker
        - git-clone-yyds
      imports:
        - https://cnb.cool/onedayxyy/secret/-/blob/main/envs.yml
      docker:
        image: docker.cnb.cool/znb/images/node:18
        volumes:
          - /data/.cache:copy-on-write
      stages:
        - name: set env
          script: echo -n $(date "+%Y-%m-%d %H:%M")
          exports:
            info: CUSTOM_ENV_DATE_INFO
        - name: ðŸ–¨ï¸ æ‰“å°çŽ¯å¢ƒ
          script: |
            node -v && npm -v && yarn -v && pnpm -v
        - name: ðŸ“¦ï¸ å®‰è£…ä¾èµ–
          script: |
            pnpm install
        - name: âš—ï¸ ç¼–è¯‘é¡¹ç›®
          script: |
            pnpm docs:build   # VitePress ä¸“ç”¨å‘½ä»¤
        - name: ðŸšš éƒ¨ç½²åˆ°Pages
          image: node:22
          script: >-
            npx edgeone pages deploy ./docs/.vitepress/dist --name
            vitepress-theme-teek --token $EDGEONE_PAGES_API_TOKEN
        - name: ðŸ”” å‘å¸ƒé€šçŸ¥
          image: tencentcom/wecom-message
          settings:
            robot: ${WECOM_BOT}
            msgType: markdown
            content: |
              > **ðŸŽ‰ Teek-oneå¼€æºåº“ åˆä¸€æ¬¡å‘å¸ƒæˆåŠŸå•¦ï¼**  
              > **æž„å»ºæ—¶é—´:** $CUSTOM_ENV_DATE_INFO          
              > **æž„å»ºid:** $CNB_BUILD_ID  
              > **æäº¤id:** $CNB_COMMIT_SHORT            
              > **æž„å»ºåˆ†æ”¯:** $CNB_BRANCH
              > **æäº¤ä¿¡æ¯:** $CNB_COMMIT_MESSAGE_TITLE
              > **æäº¤è€…:** $CNB_COMMITTER
              > **ä»“åº“åœ°å€:** [$CNB_REPO_URL_HTTPS]($CNB_REPO_URL_HTTPS)
              > **æˆ‘çš„ç½‘ç«™:** [onedayxyy.cn](https://onedayxyy.cn/)
        - name: build knowledge base
          image: cnbcool/knowledge-base
          settings:
            embedding_model: bge-m3
            include: "**/**.md"
            exclude: ""       